class Gen:
    def __init__(self, name):
        self.name = name

    def generate_tweet(self):
        # Generate a random tweet
        tweet = "This is a random tweet generated by {}".format(self.name)
        return tweet